"""initial migration

Revision ID: 0c59889cbf9f
Revises: 
Create Date: 2025-11-19 09:51:09.853244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c59889cbf9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('is_shipped', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'delivered')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'is_shipped')
    op.drop_column('orders', 'payment_at')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'is_paid')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'completed_at')
    # ### end Alembic commands ###
