"""added checkoutime

Revision ID: 1d396ea9fdd5
Revises: 3cf23a1d032c
Create Date: 2025-11-20 10:10:06.105317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d396ea9fdd5'
down_revision: Union[str, None] = '3cf23a1d032c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('checkout_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'checkout_time')
    # ### end Alembic commands ###
