"""added payment and shipping fields

Revision ID: 3cf23a1d032c
Revises: 4e76e0c9acc7
Create Date: 2025-11-20 08:38:30.277970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf23a1d032c'
down_revision: Union[str, None] = '4e76e0c9acc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_method')
    # ### end Alembic commands ###
