"""added payment and shipping fields

Revision ID: 4e76e0c9acc7
Revises: 6fb9d4f44cd9
Create Date: 2025-11-20 08:36:10.359943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e76e0c9acc7'
down_revision: Union[str, None] = '6fb9d4f44cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_provider', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('tracking_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'tracking_id')
    op.drop_column('orders', 'shipping_provider')
    op.drop_column('orders', 'payment_amount')
    # ### end Alembic commands ###
