"""added payment and shipping fields

Revision ID: 6fb9d4f44cd9
Revises: 0c59889cbf9f
Create Date: 2025-11-20 08:34:57.606791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb9d4f44cd9'
down_revision: Union[str, None] = '0c59889cbf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
